### ISSUE TITLE
Fix the errors

### ISSUE THREAD

**Issue by panosfilianos** [Destinyplyr/Exercise1_LSH#2]
Last commit has compilation errors.
See if you can resolve them. If you don't have the time, I'll get to it later today.

**Comment by vvroul** [comment]
I fixed nearly all the compilation errors. You just needed a header file with your templates, so 
Hash.cpp replaced with HashFunctions.h and included in the mainSample.h file.
Please check the changes I've made to **"initHash"** function, I think that's what you needed. 
Only the **"power" member** needs to be determined in the same function. 

Keep the good work!

**Comment by panosfilianos** [comment]
Hash.cpp remains in the project until we resolve why we have to switch to header files.
Latest commit compiles.
